# Generated by Django 4.2.3 on 2024-02-21 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_account_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='usuários'),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account', verbose_name='conta'),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='age',
            field=models.IntegerField(default=0, verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='planted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='plantado em'),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tree', verbose_name='árvore'),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, verbose_name='sobre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='entrou em'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='scientific_name',
            field=models.CharField(max_length=255, verbose_name='Nome científico'),
        ),
    ]
